### ISSUE TITLE
adjust limits in deployment causes OOMKilled

### ISSUE THREAD

**Issue by RobMokkink** [redhat-cop/patch-operator#31]
The default limits in the ```Deployment``` causes a OOMKilled.
As a workaround i removed the limits. Is it not an idea to have a custom crd to adjust the patch-operator deployment?

**Comment by davgordo** [comment]
Assuming you are using OLM Subscriptions to provision the operator, it is possible to configure custom requests and limits on the subscription resource spec.

```
spec:
  config:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

That said, if the defaults are too low under normal conditions, it would be best for us to tune them, so appreciate that feedback. Are there any special circumstances that are causing your operator instance perform any more processing than usual? Or are you seeing OOM out of the box? Also, I assume the OOM is the controller container, but please note if the OOM container is kube-rbac-proxy.
