### ISSUE TITLE
Patching objects that do not support watch

### ISSUE THREAD

**Issue by X-dark** [redhat-cop/patch-operator#36]
Hi,

I have a patch that seems to be working but on an object that do not support the watch method (ImageStreamTags). As a consequence, I am seeing a lot of error messages like:

```
E0727 12:34:19.465865       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch image.openshift.io/v1, Kind=ImageStreamTag: the server does not allow this method on the requested resource
```

What is the impact of this, feature and performance wise?

If needed my patch:

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: image-sample-scheduled-patch
  namespace: openshift
spec:
  serviceAccountRef:
    name: patchoperator-imagetag
  patches:
    image-sample-scheduled-patch:
      targetObjectRef:
        apiVersion: image.openshift.io/v1
        kind: ImageStreamTag
        namespace: openshift
      patchTemplate: |
        {{- if eq (index . 0).tag.from.kind "DockerImage" }}
        tag:
          importPolicy:
            scheduled: true
        {{- end }}
      patchType: application/strategic-merge-patch+json
```
